name: Deploy Firebase Rules

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Firebase CLI
        run: npm install -g firebase-tools


      - name: Decode and save service account credentials
        run: |
          if [[ -z "${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}" ]]; then
          echo "Error: FIREBASE_SERVICE_ACCOUNT_JSON secret is not set or empty."
          exit 1
          fi
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}" | base64 -d > $HOME/credentials.json || {
          echo "Error: Failed to decode FIREBASE_SERVICE_ACCOUNT_JSON."
          exit 1
          }
        shell: bash

      - name: Set GOOGLE_APPLICATION_CREDENTIALS environment variable
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/credentials.json" >> $GITHUB_ENV

      - name: Deploy Firestore rules
        run: firebase deploy --only firestore:rules --project awesome-biomarkers
