name: Deploy Biomarkers Bot with rollback + Telegram alerts

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh

          echo "Connecting to host: ${{ secrets.ORACLE_HOST }}"

          echo -e "${{ secrets.ORACLE_SSH_KEY }}" > ~/.ssh/github-actions
          chmod 600 ~/.ssh/github-actions
          ssh-keyscan -H ${{ secrets.ORACLE_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rollback + Telegram alerts
        run: |
          ssh -i ~/.ssh/github-actions \
              -o StrictHostKeyChecking=no \
              -o IdentitiesOnly=yes \
              ${{ secrets.ORACLE_USER }}@${{ secrets.ORACLE_HOST }} 'bash -s' << 'EOF'

            set -e
            cd ~/biomarkers

            echo "[1] Saving current commit..."
            CURRENT_COMMIT=$(git rev-parse HEAD)
            echo $CURRENT_COMMIT > .last_commit

            echo "[2] Pulling latest changes..."
            if ! git pull; then
              curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage \
                -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
                -d text="🚨 *Deploy failed during git pull* on *biomarkers bot*."
              exit 1
            fi

            echo "[3] Restarting bot service..."
            if ! sudo systemctl restart biomarkers; then
              echo "[ERR] Restart failed. Rolling back..."
              git reset --hard $(cat .last_commit)
              sudo systemctl restart biomarkers
              curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage \
                -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
                -d text="⚠️ *Rollback triggered on biomarkers bot*. Previous version restored."
              exit 1
            fi

            # Check service health
            if systemctl is-active --quiet biomarkers; then
              curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage \
                -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
                -d text="✅ *Biomarkers bot deployed successfully* and is running."
            else
              curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage \
                -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
                -d text="❌ *Biomarkers bot failed to start properly after deployment*."
              exit 1
            fi

            echo "[OK] Deployment successful."
          EOF
